version: "3"

services:
  graphdb:
    container_name: odeuropa_graphdb
    image: ontotext/graphdb:11.0.0
    restart: unless-stopped
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx32g -Xms32g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Dgraphdb.stats.default=DISABLED
        -DenablePredicateList=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - 7200:7200
    volumes:
      - ./graphdb-data:/opt/graphdb/home
      - ./dump:/opt/graphdb/home/graphdb-import
