vocabularies:
  endpoint: https://data.odeuropa.eu/repositories/odeuropa # sparql endpoint
  weights: # weights for the similarity measure of not exact matches
    alternate_labels: 0.7
    other_languages: 0.6
    unmatching_start: 0.7
  vocabularies: # list of vocabularies to include in the API
    plutchik:
      scheme: http://data.odeuropa.eu/vocabulary/plutchik
      family: emotion
    olfactory-objects:
      scheme: http://data.odeuropa.eu/vocabulary/olfactory-objects
    olfactory-gestures:
      scheme: http://data.odeuropa.eu/vocabulary/olfactory-gestures
    fragrant-spaces:
      scheme: http://data.odeuropa.eu/vocabulary/fragrant-spaces
    vdi-hedonic:
      scheme: http://data.odeuropa.eu/vocabulary/vdi-hedonic
      family: hedonic # vocabularies that are part of the same family can be queried together
    vdi-intensity:
      scheme: http://data.odeuropa.eu/vocabulary/vdi-intensity
      family: intensity # vocabularies that are part of the same family can be queried together
    edwards:
      scheme: http://data.odeuropa.eu/vocabulary/edwards
      family: character # vocabularies that are part of the same family can be queried together
      priority: 2 # low priorities are shown before in the results list for a family
    drom:
      scheme: http://data.odeuropa.eu/vocabulary/drom
      family: character
      priority: 2
    historic-book:
      scheme: http://data.odeuropa.eu/vocabulary/historic-book
      family: character
    flavornet:
      scheme: http://data.odeuropa.eu/vocabulary/flavornet
      family: character
      priority: 3
    zwaardemaker:
      scheme: http://data.odeuropa.eu/vocabulary/zwaardemaker
      family: character
      priority: 3
    dhsv-sw:
      scheme: http://data.odeuropa.eu/vocabulary/dhsv-sw
      family: character
      priority: 1
    noses:
      scheme: http://data.odeuropa.eu/vocabulary/noses
    visual-art-types:
      scheme: http://data.odeuropa.eu/vocabulary/visual-art-types
