PREFIX :<http://www.ontotext.com/connectors/lucene#>
PREFIX inst:<http://www.ontotext.com/connectors/lucene/instance#>
INSERT DATA {
	inst:search :createConnector '''
{
  "fields": [
    {
      "fieldName": "source_value",
      "propertyChain": [
        "http://erlangen-crm.org/current/P67i_is_referred_to_by",
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#value"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    },
    {
      "fieldName": "source_label",
      "propertyChain": [
        "http://erlangen-crm.org/current/P67i_is_referred_to_by",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    }
  ],
  "languages": [],
  "types": [
    "http://data.odeuropa.eu/ontology/L11_Smell"
  ],
  "readonly": false,
  "detectFields": false,
  "importGraph": false,
  "skipInitialIndexing": false,
  "boostProperties": [],
  "stripMarkup": false
}
''' .
}